const XLSX=require('xlsx');
const {parseCsv,normalizeRows,parseUploadedFile}=require('../services/importer');
const {classify}=require('../services/categorization');
const {calculateMonth,calculateVariances,reviewItems}=require('../services/financial');
const {makeCorrection}=require('../services/corrections');
const tx=(id,month,description,amount,category,extra={})=>({_id:id,externalId:id,date:new Date(`${month}-15T12:00:00Z`),description,counterparty:'Test vendor',amount,category,isPnl:true,needsReview:false,reviewed:false,...extra});

describe('CSV and Excel import',()=>{
  test('normalizes quoted fields, currency signs, IDs, and source columns',()=>{const p=normalizeRows(parseCsv('Transaction ID,Date,Description,Counterparty,Amount,Method\r\nT1,2026-01-01,"Food purchase, weekly",Sysco,"-$1,200.50",ACH'));expect(p.totalRows).toBe(1);expect(p.rows[0]).toMatchObject({externalId:'T1',description:'Food purchase, weekly',counterparty:'Sysco',amount:-1200.5,paymentMethod:'ACH',category:'Needs Review'});});
  test('returns row-level errors and rejects missing required headers',()=>{const p=normalizeRows([['Date','Description','Amount'],['bad','Rent','x'],['2026-01-01','',2]]);expect(p.errors).toHaveLength(2);expect(normalizeRows([['id','amount']]).errors[0].message).toMatch(/date, desc, amount/);});
  test('parses XLSX data rows',()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Transaction ID','Date','Description','Counterparty','Amount','Method'],['T9','2026-02-02','Rent','Landlord',-500,'ACH']]),'Sheet1');const p=parseUploadedFile(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),'t.xlsx');expect(p.rows[0]).toMatchObject({externalId:'T9',amount:-500,category:'Rent',confidence:.99});});
});
describe('restaurant categories and corrections',()=>{
  test.each([['Rent','Rent',false],['POS batch deposit - food sales week 1','Food Sales',false],['Gift card sales deposit','Gift Card Liability',true],['Loan principal repayment','Loan Principal',true],['unknown transfer','Needs Review',true]])('classifies %s', (description,category,needsReview)=>expect(classify({description,counterparty:'',amount:-100})).toMatchObject({category,needsReview}));
  test('manual category changes include persistence metadata and history',()=>{const c=makeCorrection({category:'Food & Ingredients',originalCategory:'Food & Ingredients'},'Marketing',{reason:'Reviewed invoice'});expect(c).toMatchObject({category:'Marketing',originalCategory:'Food & Ingredients',classificationMethod:'manual',isPnl:true});expect(c.correction).toMatchObject({fromCategory:'Food & Ingredients',toCategory:'Marketing',reason:'Reviewed invoice'});expect(()=>makeCorrection({category:'Rent'},'Unknown')).toThrow(/supported/);});
  test('only unresolved review items remain in the queue',()=>{const rows=[tx('1','2026-01','Loan',-500,'Loan Principal',{isPnl:false,needsReview:true}),tx('2','2026-01','Reviewed',-1,'Needs Review',{needsReview:true,reviewed:true})];expect(reviewItems(rows).map(x=>x.externalId)).toEqual(['1']);});
});
describe('deterministic financial services',()=>{
  const rows=[tx('a','2026-01','food sales',1000,'Food Sales'),tx('b','2026-01','beverage sales',500,'Beverage Sales'),tx('c','2026-01','refunds',-100,'Sales Returns & Discounts'),tx('d','2026-01','ingredients',-200,'Food & Ingredients'),tx('e','2026-01','beverage inventory',-50,'Beverage Inventory'),tx('f','2026-01','packaging',-50,'Packaging & Disposables'),tx('g','2026-01','wages',-300,'Payroll Wages'),tx('h','2026-01','payroll taxes',-30,'Payroll Taxes & Benefits'),tx('i','2026-01','rent',-100,'Rent'),tx('j','2026-01','utilities',-20,'Utilities'),tx('k','2026-01','loan',-900,'Loan Principal',{isPnl:false})];
  test('calculates revenue, COGS, gross profit, payroll, operating expenses and operating profit',()=>expect(calculateMonth(rows,'2026-01')).toMatchObject({revenue:1400,cogs:300,grossProfit:1100,payroll:330,operatingExpenses:120,operatingProfit:650}));
  test('provides evidence IDs and excludes non-P&L transactions',()=>expect(calculateMonth(rows,'2026-01').evidenceIds).toEqual(['a','b','c','d','e','f','g','h','i','j']));
  test('calculates variances, relative changes, materiality and ranked drivers',()=>{const pnl=[{month:'2026-01',revenue:1000,cogs:200,grossProfit:800,payroll:300,operatingExpenses:100,operatingProfit:400,categoryTotals:{'Food & Ingredients':200,Rent:100}},{month:'2026-02',revenue:1800,cogs:500,grossProfit:1300,payroll:300,operatingExpenses:200,operatingProfit:800,categoryTotals:{'Food & Ingredients':500,Rent:200}}];const v=calculateVariances(pnl)[0];expect(v.metrics.find(x=>x.metric==='cogs')).toMatchObject({change:300,percent:150,material:false});expect(v.metrics.find(x=>x.metric==='revenue')).toMatchObject({change:800,percent:80,material:true});expect(v.drivers[0]).toMatchObject({category:'Food & Ingredients',change:300,profitImpact:-300});});
});
